### ISSUE TITLE
Intermittent issues while adding recurring jobs

### ISSUE THREAD

**Issue by cocowalla** [ahydrax/Hangfire.PostgreSql#12]
I have a cluster of Hangfire servers, which call `RecurringJob.AddOrUpdate` during startup to add recurring jobs. When the servers start at roughly the same time, I sometimes get some kind of concurrency error, `could not serialize access due to concurrent update`:

```
Unhandled Exception: Npgsql.PostgresException: 40001: could not serialize access due to concurrent update
   at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext() in C:\projects\npgsql\src\Npgsql\NpgsqlConnector.cs:line 1032
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming) in C:\projects\npgsql\src\Npgsql\NpgsqlDataReader.cs:line 467
   at Npgsql.NpgsqlDataReader.NextResult() in C:\projects\npgsql\src\Npgsql\NpgsqlDataReader.cs:line 332
   at Npgsql.NpgsqlCommand.ExecuteDbDataReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken) in C:\projects\npgsql\src\Npgsql\NpgsqlCommand.cs:line 1219
   at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken) in C:\projects\npgsql\src\Npgsql\NpgsqlCommand.cs:line 1042
   at Npgsql.NpgsqlCommand.ExecuteNonQuery() in C:\projects\npgsql\src\Npgsql\NpgsqlCommand.cs:line 1025
   at Dapper.SqlMapper.ExecuteCommand(IDbConnection cnn, CommandDefinition& command, Action`2 paramReader) in C:\projects\dapper\Dapper\SqlMapper.cs:line 2827
   at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command) in C:\projects\dapper\Dapper\SqlMapper.cs:line 570
   at Dapper.SqlMapper.Execute(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType) in C:\projects\dapper\Dapper\SqlMapper.cs:line 443
   at Hangfire.PostgreSql.WriteOnlyTransaction.<>c__DisplayClass20_1.<SetRangeInHash>b__0(NpgsqlConnection con, NpgsqlTransaction trx) in C:\MyPath\src\\Hangfire.PostgreSql\src\Hangfire.PostgreSql\WriteOnlyTransaction.cs:line 240
   at Hangfire.PostgreSql.WriteOnlyTransaction.Commit() in C:\MyPath\src\Hangfire.PostgreSql\WriteOnlyTransaction.cs:line 40
   at Hangfire.RecurringJobManager.AddOrUpdate(String recurringJobId, Job job, String cronExpression, RecurringJobOptions options)
   at MyNamespace.Program.RunWithoutDashboard() in C:\MyPath\Program.cs:line 48
   at MyNamespace.Program.Main(String[] args) in C:\MyPathe\Program.cs:line 39
   at MyNamespace.Program.<Main>(String[] args)

```

I get this with both Ngqsql 3.x and 4.x.

There's an [old issue](https://github.com/frankhommers/Hangfire.PostgreSql/issues/4) in the original repo that might be relevant, and a [newer one](https://github.com/frankhommers/Hangfire.PostgreSql/issues/73) that certainly is.

**Comment by ahydrax** [comment]
Hi @cocowalla ,

Thanks for report, I'll look into that.

**Comment by cocowalla** [comment]
It might be obvious, but I should also add that this is only happening when the servers are all using the same job IDs - that is, the servers are calling `RecurringJob.AddOrUpdate` on the same job IDs.
