### ISSUE TITLE
Upgrade npgsql to 4.0.2

### ISSUE THREAD

**Issue by Yanal-Yves** [ahydrax/Hangfire.PostgreSql#5]
According to the release notes, the 4.0 release has major performance boost:
http://www.npgsql.org/doc/release-notes/4.0.html

Need a new version of hangfire.postgresql that uses the new version and also supports .net core 2.0/2.1.

**Comment by ahydrax** [comment]
Hi @Yanal-Yves , I'm not sure if npgsql 4 is stable enough now. Do you use it in production?

**Comment by ahydrax** [comment]
Closed until response.

**Comment by Yanal-Yves** [comment]
Hello @ahydrax,
Sorry for this late response.

Unfortunately, I did not try npgsql 4 in production yet.

The reason why I am asking is because I want to use Hangfire in a project using Entity Framework Core 2.1.1. To use Entity Framework Core 2.1.1 I have included Npgsql.EntityFrameworkCore.PostgreSQL 2.1.1.1 which has a dependency to NpgSQL 4.0.2.

So I cannot have in the same project NpgSQL 4.0.2 and NpgSQL 3.2.5. This is why I am asking if you can upgrade the version of NpgSQL in Hangfire.PostgreSql.ahydrax.

**Comment by ahydrax** [comment]
Hi @Yanal-Yves,

I've created special [build ](https://www.nuget.org/packages/Hangfire.PostgreSql.ahydrax/1.6.0-betanpgsql4) on top of npgsql4.

**Comment by Yanal-Yves** [comment]
Hello @ahydrax,

Thank you for this build.

I am getting this exception after upgrading to the last build:

```
Application startup exception: System.ArgumentException: Invalid Postgres connection string: Search Path has not found.
   at Hangfire.PostgreSql.Guard.ThrowIfConnectionStringIsInvalid(String connectionString)
   at Hangfire.PostgreSql.PostgreSqlStorage..ctor(String connectionString, PostgreSqlStorageOptions options)
   at Hangfire.PostgreSql.PostgreSqlBootstrapperConfigurationExtensions.UsePostgreSqlStorage(IGlobalConfiguration configuration, String nameOrConnectionString)
   at Prothesis.Hangfire.Startup.<>c__DisplayClass10_0.<ConfigureServices>b__1(IGlobalConfiguration x) in C:\_src\ProthesisDentalSolutions\Prothesis\src\Prothesis.Hangfire\Startup.cs:line 111
   at Hangfire.HangfireServiceCollectionExtensions.<>c__DisplayClass0_0.<AddHangfire>b__9(IServiceProvider serviceProvider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton(SingletonCallSite singletonCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Hangfire.HangfireApplicationBuilderExtensions.ThrowIfNotConfigured(IApplicationBuilder app)
   at Hangfire.HangfireApplicationBuilderExtensions.UseHangfireDashboard(IApplicationBuilder app, String pathMatch, DashboardOptions options, JobStorage storage)
   at Prothesis.Hangfire.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env) in C:\_src\ProthesisDentalSolutions\Prothesis\src\Prothesis.Hangfire\Startup.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
crit: Microsoft.AspNetCore.Hosting.Internal.WebHost[6]
      Application startup exception
```

My connection string is `Server=localhost;Port=5432;Database=my_database;User Id=my_user;Password=my_password;`

Any idea what am I doing wrong?

**Comment by ahydrax** [comment]
Hi @Yanal-Yves , you need to specify `Search Path` parameter in connection string which is name of schema used for hangfire tables. Usually it's named `hangfire`.

**Comment by Yanal-Yves** [comment]
Hi @ahydrax, 

Thank you for your quick answer.

I have just tried and it's now working like a charm.

Have a good day!
