### ISSUE TITLE
DistributedLockException on the Hangfire client  side

### ISSUE THREAD

**Issue by ilya-chumakov** [ahydrax/Hangfire.PostgreSql#7]
The latest beta `1.6.0-beta2` throws an exception when initializing the storage for a Hangfire client:

        GlobalConfiguration
            .Configuration
            .UsePostgreSqlStorage(options.ConnectionString);

 DelayedJobScheduler      Error occurred during execution of 'DelayedJobScheduler' process. Execution will be retried (attempt #2) in 00:00:02 seconds.
Hangfire.PostgreSql.DistributedLockException: Could not place a lock on the resource 'hangfire:locks:schedulepoller': Lock timeout.
   at Hangfire.PostgreSql.DistributedLock.Initialize()
   at Hangfire.PostgreSql.DistributedLock..ctor(String resource, TimeSpan timeout, IConnectionProvider connectionProvider)
   at Hangfire.PostgreSql.StorageConnection.AcquireDistributedLock(String resource, TimeSpan timeout)
   at Hangfire.Server.DelayedJobScheduler.UseConnectionDistributedLock[T](JobStorage storage, Func`2 action)
   at Hangfire.Server.DelayedJobScheduler.Execute(BackgroundProcessContext context)
   at Hangfire.Server.AutomaticRetryProcess.Execute(BackgroundProcessContext context)

**Comment by ahydrax** [comment]
@ilya-chumakov will look into that, thanks.

**Comment by ahydrax** [comment]
@ilya-chumakov new beta is on nuget. Could you check if your problem is resolved?
